const  felix = {
  mail: 'felix@mail.com',
  pass: '123456',
  name: 'felix',
  lastName: 'tineo',
  birthday: '13/05/1986',
  history: 'Soy un entuciasta al desarrollo web, tsu en informatica. Mis primeros acercamientos con la programacion fue a los 16 años, llevo 17 años en esto como hobbie y 5 años dedicandome al desarrollo web de manera profesional',
  interest: 'Me gusta tocar la guitarra, salir con amigos, trabajar y trabajar para ser mejor en mi campo',
  perfilImg: '/static/felix.jpg',
  frontPageImg: '/static/bg-felix.jpg',
  frontPageQuote:'-Vivimos en la tierra como si tuviéramos otra a la que ir.-Terry Swearingen.',
  wallet: 500,
  posts: [],
  friends: [],
  friendReq: [],
  gifts: 10,
  comments: [],
}
const admin = {
  mail: 'admin@mail.com',
  pass: '123456',
  name: 'admin',
  lastName: 'default',
  birthday: '13/07/2019',
  history: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, nobis! Officiis distinctio in aliquid, deleniti facilis hic animi incidunt ab nulla soluta et unde accusantium expedita sed debitis impedit est!',
  interest: 'Lorem ipsum dolor sit amet consectetur',
  perfilImg: '/static/admin.jpg',
  frontPageImg: '/static/queenfront.jpg',
  frontPageQuote:'-Vivimos en la tierra como si tuviéramos otra a la que ir.-Terry Swearingen.',
  wallet: 500,
  posts: [],
  friends: [],
  friendReq: [],
  gifts: 10,
  comments: [],
}
const  person1 = {
  mail: 'person1@mail.com',
  pass: '123456',
  name: 'jhon',
  lastName: 'doe',
  birthday: '13/07/2019',
  history: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, nobis! Officiis distinctio in aliquid, deleniti facilis hic animi incidunt ab nulla soluta et unde accusantium expedita sed debitis impedit est!',
  interest: 'Lorem ipsum dolor sit amet consectetur',
  perfilImg: '/static/friend-1.jpg',
  frontPageImg: '/static/queenfront.jpg',
  frontPageQuote:'-Vivimos en la tierra como si tuviéramos otra a la que ir.-Terry Swearingen.',
  wallet: 500,
  posts: [],
  friends: [],
  friendReq: [],
  gifts: 10,
  comments: [],
}

const  person2 = {
  mail: 'person2@mail.com',
  pass: '123456',
  name: 'jhoanna',
  lastName: 'water',
  birthday: '13/07/2019',
  history: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, nobis! Officiis distinctio in aliquid, deleniti facilis hic animi incidunt ab nulla soluta et unde accusantium expedita sed debitis impedit est!',
  interest: 'Lorem ipsum dolor sit amet consectetur',
  perfilImg: '/static/friend-2.jpg',
  frontPageImg: '/static/queenfront.jpg',
  frontPageQuote:'-El activista no es quien dice que el río esta sucio. El activista es quien limpia el río.-Ross Perot.',
  wallet: 500,
  posts: [],
  friends: [],
  friendReq: [],
  gifts: 10,
  comments: [],
}
const  person3 = {
  mail: 'person3@mail.com',
  pass: '123456',
  name: 'jhenna',
  lastName: 'fire',
  birthday: '13/07/2019',
  history: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, nobis! Officiis distinctio in aliquid, deleniti facilis hic animi incidunt ab nulla soluta et unde accusantium expedita sed debitis impedit est!',
  interest: 'Lorem ipsum dolor sit amet consectetur',
  perfilImg: '/static/friend-3.jpg',
  frontPageImg: '/static/queenfront.jpg',
  frontPageQuote:'-El mundo no va a sobrevivir mucho más tiempo como cautivo de la humanidad.-Daniel Quinn.',
  wallet: 500,
  posts: [],
  friends: [],
  friendReq: [],
  gifts: 10,
  comments: [],
}
const  person4 = {
  mail: 'person4@mail.com',
  pass: '123456',
  name: 'thera',
  lastName: 'earth',
  birthday: '13/07/2019',
  history: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, nobis! Officiis distinctio in aliquid, deleniti facilis hic animi incidunt ab nulla soluta et unde accusantium expedita sed debitis impedit est!',
  interest: 'Lorem ipsum dolor sit amet consectetur',
  perfilImg: '/static/friend-4.jpg',
  frontPageImg: '/static/queenfront.jpg',
  frontPageQuote:'-La conservación es un estado de armonía entre hombre y tierra.-Aldo Leopold.',
  wallet: 500,
  posts: [],
  friends: [],
  friendReq: [],
  gifts: 10,
  comments: [],
};

const persons = [felix, admin, person1, person2, person3, person4 ];

module.exports = persons;
